import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";
import { signedUsageJobNonce, usageJobSignedHeaders } from "../features/usage/job-auth";
import type { UsageQuery } from "../lib/usage-postgres";
import { changeUsageScheduler, configureUsageScheduler, usageSchedulerCommand, usageSchedulerName, usageSchedulerOrigin, usageSchedulerStatus } from "../lib/usage-scheduler";

const origin = "https://main.fixture.amplifyapp.com";
const secret = "fixture_cron_credential_with_at_least_32_characters";
const schedulerMigration = () => readFile(new URL("../supabase/migrations/202610040001_everonn_usage_scheduler.sql", import.meta.url), "utf8");

test("consolidation keeps the live scheduler, secret and job unchanged; reconfiguration targets the new tables", async () => {
  const {db,query}=await fixture();
  try {
    const migration=await schedulerMigration();
    await configureUsageScheduler(query,{origin,secret,migration});
    await changeUsageScheduler(query,true,{origin,secret});
    const jobs=await query("SELECT * FROM cron.job ORDER BY jobid");
    const secrets=await query("SELECT * FROM vault.secrets ORDER BY id");
    const [first]=await query<{id:number}>("SELECT everonn_usage.invoke_usage_worker() AS id");
    await query("INSERT INTO net._http_response(id,status_code,created) VALUES ($1,200,now())",[first.id]);
    await db.exec(await readFile(new URL("../supabase/migrations/202610040002_everonn_app.sql",import.meta.url),"utf8"));
    await db.exec(await readFile(new URL("../supabase/migrations/202610040003_everonn_relational.sql",import.meta.url),"utf8"));
    assert.deepEqual(await query("SELECT * FROM cron.job ORDER BY jobid"),jobs);
    assert.deepEqual(await query("SELECT * FROM vault.secrets ORDER BY id"),secrets);
    assert.equal((await usageSchedulerStatus(query)).active,true);
    const [second]=await query<{id:number}>("SELECT everonn_usage.invoke_usage_worker() AS id");
    assert.ok(second.id>first.id);
    assert.equal((await query("SELECT * FROM everonn.worker_requests")).length,2);
    await query("INSERT INTO net._http_response(id,status_code,created) VALUES ($1,200,now())",[second.id]);
    await db.exec("INSERT INTO everonn.usage_job_nonces(key,payload,updated_at) VALUES ('system/job-auth/expired','{}',now()-interval '9 days')");
    const [third]=await query<{id:number}>("SELECT everonn_usage.invoke_usage_worker() AS id");
    assert.ok(third.id>second.id);
    assert.equal((await query("SELECT * FROM everonn.usage_job_nonces")).length,0);
    await configureUsageScheduler(query,{origin,secret,migration});
    await changeUsageScheduler(query,true,{origin,secret});
    assert.equal((await usageSchedulerStatus(query)).active,true);
    assert.deepEqual(await query("SELECT * FROM cron.job WHERE jobname='other_project'"),jobs.filter(row=>row.jobname==="other_project"));
    assert.deepEqual(await query("SELECT * FROM vault.secrets WHERE name='other_project'"),secrets.filter(row=>row.name==="other_project"));
  } finally {await db.close();}
});

async function fixture() {
  const db = new PGlite({ extensions: { pgcrypto } });
  await db.exec(`
    CREATE SCHEMA extensions; CREATE EXTENSION pgcrypto WITH SCHEMA extensions;
    CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;
    CREATE SCHEMA agentic_that;
    CREATE TABLE public.existing_data(id integer PRIMARY KEY, value text);
    INSERT INTO public.existing_data VALUES (1,'retained');
    CREATE TABLE agentic_that.existing_data(value text);
    INSERT INTO agentic_that.existing_data VALUES ('retained');
    CREATE SCHEMA vault; CREATE SCHEMA cron; CREATE SCHEMA net;
    REVOKE ALL ON SCHEMA vault,cron,net FROM PUBLIC;
    CREATE TABLE vault.secrets(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text UNIQUE, description text, decrypted_secret text, updated_at timestamptz DEFAULT now());
    CREATE VIEW vault.decrypted_secrets AS SELECT * FROM vault.secrets;
    CREATE FUNCTION vault.create_secret(secret text,name text,description text) RETURNS uuid LANGUAGE sql AS $$
      INSERT INTO vault.secrets(name,description,decrypted_secret) VALUES (name,description,secret) RETURNING id
    $$;
    CREATE FUNCTION vault.update_secret(secret_id uuid,secret text,new_name text,new_description text) RETURNS void LANGUAGE sql AS $$
      UPDATE vault.secrets SET decrypted_secret=secret,name=new_name,description=new_description,updated_at=now() WHERE id=secret_id
    $$;
    SELECT vault.create_secret('unrelated-secret','other_project','Existing project');
    CREATE TABLE cron.job(jobid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,jobname text UNIQUE,schedule text,command text,active boolean DEFAULT true,username text DEFAULT current_user,database text DEFAULT current_database());
    CREATE TABLE cron.job_run_details(jobid bigint,status text,start_time timestamptz,end_time timestamptz);
    CREATE FUNCTION cron.schedule(name text,schedule text,command text) RETURNS bigint LANGUAGE sql AS $$
      INSERT INTO cron.job(jobname,schedule,command) VALUES (name,schedule,command)
      ON CONFLICT (jobname) DO UPDATE SET schedule=EXCLUDED.schedule,command=EXCLUDED.command,active=true RETURNING jobid
    $$;
    CREATE FUNCTION cron.alter_job(job_id bigint,active boolean) RETURNS void LANGUAGE sql AS $$ UPDATE cron.job SET active=$2 WHERE jobid=job_id $$;
    SELECT cron.schedule('other_project','0 * * * *','SELECT 1;');
    INSERT INTO cron.job_run_details SELECT jobid,'succeeded',now()-interval '9 days',now()-interval '9 days' FROM cron.job WHERE jobname='other_project';
    CREATE TABLE net.http_request_queue(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,url text,body jsonb,headers jsonb,timeout_milliseconds integer);
    CREATE TABLE net._http_response(id bigint,status_code integer,timed_out boolean,error_msg text,created timestamptz);
    CREATE FUNCTION net.http_post(url text,body jsonb DEFAULT '{}',params jsonb DEFAULT '{}',headers jsonb DEFAULT '{}',timeout_milliseconds integer DEFAULT 2000)
      RETURNS bigint LANGUAGE sql AS $$ INSERT INTO net.http_request_queue(url,body,headers,timeout_milliseconds) VALUES (url,body,headers,timeout_milliseconds) RETURNING id $$;
  `);
  await db.exec(await readFile(new URL("../supabase/migrations/202610030001_everonn_usage.sql", import.meta.url), "utf8"));
  const query: UsageQuery = async <T extends Record<string, unknown>>(statement: string, parameters: unknown[] = []) => {
    if (statement.includes("pg_available_extensions")) return ["pg_cron", "pg_net", "supabase_vault"].map(name => ({ name, installed: true })) as unknown as T[];
    // PGlite's parameterized query uses the extended protocol; migrations use
    // the simple protocol, as the real driver's unprepared unsafe() does.
    if (statement.includes("DO $guard$")) { await db.exec(statement); return []; }
    return (await db.query<T>(statement, parameters)).rows;
  };
  return { db, query };
}

test("scheduler config is idempotent, private, and preserves existing data, jobs and Vault secrets", async () => {
  const { db, query } = await fixture();
  try {
    const otherJobs = await query("SELECT * FROM cron.job WHERE jobname='other_project'");
    const otherSecrets = await query("SELECT * FROM vault.secrets WHERE name='other_project'");
    const options = { origin, secret, migration: await schedulerMigration() };
    const first = await configureUsageScheduler(query, options);
    await changeUsageScheduler(query, true, { origin, secret });
    const second = await configureUsageScheduler(query, options);
    assert.equal(first.jobId, second.jobId);
    assert.equal(second.active, false, "reconfiguration pauses the schedule until the live worker is verified");
    assert.deepEqual(await query("SELECT * FROM cron.job WHERE jobname='other_project'"), otherJobs);
    assert.deepEqual(await query("SELECT * FROM vault.secrets WHERE name='other_project'"), otherSecrets);
    assert.deepEqual(await query("SELECT * FROM public.existing_data"), [{ id: 1, value: "retained" }]);
    assert.deepEqual(await query("SELECT * FROM agentic_that.existing_data"), [{ value: "retained" }]);
    const [job] = await query<{ command: string; schedule: string; active: boolean }>("SELECT command,schedule,active FROM cron.job WHERE jobname=$1", [usageSchedulerName]);
    assert.deepEqual(job, { command: usageSchedulerCommand, schedule: "* * * * *", active: false });
    assert.ok(!JSON.stringify(job).includes(secret));
    for (const role of ["anon", "authenticated", "service_role"]) {
      await db.exec(`SET ROLE ${role}`);
      await assert.rejects(db.query("SELECT * FROM everonn_usage.worker_requests"), /permission denied/);
      await assert.rejects(db.query("SELECT everonn_usage.invoke_usage_worker()"), /permission denied/);
      await db.exec("RESET ROLE");
    }
    await assert.rejects(changeUsageScheduler(query, true, { origin, secret: `${secret}_wrong` }), /do not match/);
    assert.equal((await query<{ active: boolean }>("SELECT active FROM cron.job WHERE jobname=$1", [usageSchedulerName]))[0].active, false);
    await changeUsageScheduler(query, true, { origin, secret });
    assert.equal((await usageSchedulerStatus(query)).active, true);
  } finally { await db.close(); }
});

test("worker queues a compatible short-lived signature, avoids overlapping requests, and scopes retention", async () => {
  const { db, query } = await fixture();
  const originalSecret = process.env.USAGE_CRON_SECRET;
  process.env.USAGE_CRON_SECRET = secret;
  try {
    await configureUsageScheduler(query, { origin, secret, migration: await schedulerMigration() });
    const [first] = await query<{ id: number }>("SELECT everonn_usage.invoke_usage_worker() AS id");
    const [request] = await query<{ url: string; headers: Record<string, string>; timeout_milliseconds: number }>("SELECT url,headers,timeout_milliseconds FROM net.http_request_queue WHERE id=$1", [first.id]);
    assert.equal(request.url, `${origin}/api/usage/jobs`);
    assert.equal(request.headers.Authorization, undefined);
    assert.ok(!JSON.stringify(request).includes(secret), "the permanent credential never enters the public HTTP queue");
    assert.equal(signedUsageJobNonce(new Request(request.url, { method: "POST", headers: request.headers })), request.headers["x-everonn-usage-nonce"]);
    assert.equal(request.timeout_milliseconds, 65000);
    assert.equal((await query<{ id: number | null }>("SELECT everonn_usage.invoke_usage_worker() AS id"))[0].id, null);
    await query("INSERT INTO net._http_response(id,status_code,created) VALUES ($1,200,now())", [first.id]);
    await query("INSERT INTO cron.job_run_details SELECT jobid,'succeeded',now()-interval '9 days',now()-interval '9 days' FROM cron.job WHERE jobname=$1", [usageSchedulerName]);
    assert.ok((await query<{ id: number }>("SELECT everonn_usage.invoke_usage_worker() AS id"))[0].id > first.id);
    assert.equal((await query("SELECT * FROM cron.job_run_details WHERE jobid=(SELECT jobid FROM cron.job WHERE jobname=$1)", [usageSchedulerName])).length, 0);
    assert.equal((await query("SELECT * FROM cron.job_run_details WHERE jobid=(SELECT jobid FROM cron.job WHERE jobname='other_project')")).length, 1);
    const status = await usageSchedulerStatus(query);
    assert.ok(!JSON.stringify(status).includes(secret), "status never prints credentials, headers or response bodies");
    assert.equal(status.requests?.[1].status_code, 200);
    // A transport outage cannot prevent all future ticks indefinitely.
    await db.exec("UPDATE everonn_usage.worker_requests SET requested_at=now()-interval '2 minutes'");
    assert.ok((await query<{ id: number }>("SELECT everonn_usage.invoke_usage_worker() AS id"))[0].id);
  } finally { if (originalSecret === undefined) delete process.env.USAGE_CRON_SECRET; else process.env.USAGE_CRON_SECRET = originalSecret; await db.close(); }
});

test("setup stops on occupied scheduler objects, foreign job names, secrets and unsafe shared extension access", async () => {
  for (const setup of [
    "SELECT vault.create_secret('do-not-change','everonn_usage_worker_v1','Another project');",
    "SELECT cron.schedule('everonn_usage_worker_v1','0 * * * *','SELECT 123;');",
    "CREATE TABLE everonn_usage.worker_requests(unrelated text);",
    "GRANT SELECT ON vault.decrypted_secrets TO anon;",
  ]) {
    const { db, query } = await fixture();
    try {
      await db.exec(setup);
      const original = await query("SELECT * FROM cron.job ORDER BY jobid");
      const secrets = await query("SELECT * FROM vault.secrets ORDER BY id");
      await db.exec("BEGIN");
      await assert.rejects(configureUsageScheduler(query, { origin, secret, migration: await schedulerMigration() }), /unrecognized|Unrecognized|Browser roles/);
      await db.exec("ROLLBACK");
      assert.deepEqual(await query("SELECT * FROM cron.job ORDER BY jobid"), original);
      assert.deepEqual(await query("SELECT * FROM vault.secrets ORDER BY id"), secrets);
    } finally { await db.close(); }
  }
});

test("job signatures reject tampering, expiry, future timestamps, other methods and paths", () => {
  const previous = process.env.USAGE_CRON_SECRET;
  process.env.USAGE_CRON_SECRET = secret;
  const now = Date.now();
  const headers = usageJobSignedHeaders(secret, now);
  const request = (h = headers, method = "POST", path = "/api/usage/jobs") => new Request(`${origin}${path}`, { method, headers: h });
  try {
    assert.equal(signedUsageJobNonce(request(), now), headers["x-everonn-usage-nonce"]);
    assert.equal(signedUsageJobNonce(request({ ...headers, "x-everonn-usage-nonce": "11111111-1111-4111-8111-111111111111" }), now), null);
    assert.equal(signedUsageJobNonce(request({ ...headers, "x-everonn-usage-signature": "0".repeat(64) }), now), null);
    assert.equal(signedUsageJobNonce(request(usageJobSignedHeaders(secret, now - 181_000)), now), null);
    assert.equal(signedUsageJobNonce(request(usageJobSignedHeaders(secret, now + 31_000)), now), null);
    assert.equal(signedUsageJobNonce(request(headers, "GET"), now), null);
    assert.equal(signedUsageJobNonce(request(headers, "POST", "/api/other"), now), null);
  } finally { if (previous === undefined) delete process.env.USAGE_CRON_SECRET; else process.env.USAGE_CRON_SECRET = previous; }
});

test("scheduler accepts only a public HTTPS origin", () => {
  assert.equal(usageSchedulerOrigin(`${origin}/`), origin);
  for (const value of ["http://example.com", "https://localhost", "https://127.0.0.1", "https://server.local", `${origin}/api/usage/jobs`, `${origin}?secret=x`, "https://user:pass@example.com"]) {
    assert.throws(() => usageSchedulerOrigin(value), /HTTPS origin/);
  }
});
